run:
  deadline: 5m
  build-tags:
    - integration

linters:
  enable:
    - asciicheck
    - bodyclose
    # - cyclop TODO calculated cyclomatic complexity
    - deadcode
    - dupl
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    #- gofmt TODO
    #- goimports TODO
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"

    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in package names"

    - linters:
        - revive
      text: "var-naming: don't use an underscore in package name"

  exclude:
    - Using the variable on range scope .* in function literal
    - Top level comment should end in a period
