name: codecov

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  codecov:
    timeout-minutes: 15

    services:
      pulsar:
        image: apachepulsar/pulsar-standalone:2.8.4
        ports:
          - 6650:6650
          - 8080:8080

    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: go version && go mod download

      # sleep to make sure that pulsar container is ready
      - name: Run tests with coverage
        run: sleep 20 && make test-integration-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./.testCoverage
