name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    timeout-minutes: 15

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19]

    services:
      pulsar:
        image: apachepulsar/pulsar-standalone:2.8.4
        ports:
          - 6650:6650
          - 8080:8080

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install linters
        run: make install-linter

      - name: Get dependencies
        run: go mod download

      # sleep to make sure that pulsar container is ready
      - name: Run tests
        run: sleep 20 && make test-integration

      - name: Run linter
        run: make lint
