name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    timeout-minutes: 15

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.14, 1.15]

    services:
      pulsar:
        image: codejuggle/pulsar-docker-standalone:latest
        ports:
          - 6650:6650

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -tags integration -race -count 10 -v .

      - name: Install linter
        run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0"

      - name: Run linter
        run: golangci-lint run
